
export enum FanKind {
  APP = 1,
  NAT,
  FUN,
  THUNK,
  DAT,
}

export enum DatKind {
  PIN,
  ROW,
  TAB,
  BAR,
  COW,
  CAB
};

export type Nat = bigint;

// The type of a function implementation. This is actually something like
// (Fan[]) => Fan, but typescript gets really hung up on the apply() based
// calling convention of our autogenerated code.
export type Fun = any;

export type Fan =
  | { t: FanKind.APP; f:Fan; x:Fan }
  | { t: FanKind.NAT; v:Nat }
  | { t: FanKind.FUN; n:Nat; a:Nat; b:Fan; x:Fun }
  | { t: FanKind.THUNK; x:() => void }
  | { t: FanKind.DAT; d:Dat }

export type Dat =
  | { t: DatKind.PIN; i:Fan; x:Fun }
  | { t: DatKind.ROW; r:Fan[] }
  | { t: DatKind.COW; z:Nat }



// Local Variables:
// typescript-indent-level: 2
// End:
// vim: noai:ts=2:sw=2

